/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypeSlugRouteRouteImport } from './routes/$type/$slug/route'
import { Route as TypeSlugIndexRouteImport } from './routes/$type/$slug/index'
import { Route as TypeSlugPortcosIndexRouteImport } from './routes/$type/$slug/portcos/index'
import { Route as TypeSlugChatChatIdIndexRouteImport } from './routes/$type/$slug/chat/$chatId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeSlugRouteRoute = TypeSlugRouteRouteImport.update({
  id: '/$type/$slug',
  path: '/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeSlugIndexRoute = TypeSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TypeSlugRouteRoute,
} as any)
const TypeSlugPortcosIndexRoute = TypeSlugPortcosIndexRouteImport.update({
  id: '/portcos/',
  path: '/portcos/',
  getParentRoute: () => TypeSlugRouteRoute,
} as any)
const TypeSlugChatChatIdIndexRoute = TypeSlugChatChatIdIndexRouteImport.update({
  id: '/chat/$chatId/',
  path: '/chat/$chatId/',
  getParentRoute: () => TypeSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$type/$slug': typeof TypeSlugRouteRouteWithChildren
  '/$type/$slug/': typeof TypeSlugIndexRoute
  '/$type/$slug/portcos/': typeof TypeSlugPortcosIndexRoute
  '/$type/$slug/chat/$chatId/': typeof TypeSlugChatChatIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$type/$slug': typeof TypeSlugIndexRoute
  '/$type/$slug/portcos': typeof TypeSlugPortcosIndexRoute
  '/$type/$slug/chat/$chatId': typeof TypeSlugChatChatIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$type/$slug': typeof TypeSlugRouteRouteWithChildren
  '/$type/$slug/': typeof TypeSlugIndexRoute
  '/$type/$slug/portcos/': typeof TypeSlugPortcosIndexRoute
  '/$type/$slug/chat/$chatId/': typeof TypeSlugChatChatIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$type/$slug'
    | '/$type/$slug/'
    | '/$type/$slug/portcos/'
    | '/$type/$slug/chat/$chatId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/$type/$slug' | '/$type/$slug/portcos' | '/$type/$slug/chat/$chatId'
  id:
    | '__root__'
    | '/'
    | '/$type/$slug'
    | '/$type/$slug/'
    | '/$type/$slug/portcos/'
    | '/$type/$slug/chat/$chatId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TypeSlugRouteRoute: typeof TypeSlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$type/$slug': {
      id: '/$type/$slug'
      path: '/$type/$slug'
      fullPath: '/$type/$slug'
      preLoaderRoute: typeof TypeSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$type/$slug/': {
      id: '/$type/$slug/'
      path: '/'
      fullPath: '/$type/$slug/'
      preLoaderRoute: typeof TypeSlugIndexRouteImport
      parentRoute: typeof TypeSlugRouteRoute
    }
    '/$type/$slug/portcos/': {
      id: '/$type/$slug/portcos/'
      path: '/portcos'
      fullPath: '/$type/$slug/portcos/'
      preLoaderRoute: typeof TypeSlugPortcosIndexRouteImport
      parentRoute: typeof TypeSlugRouteRoute
    }
    '/$type/$slug/chat/$chatId/': {
      id: '/$type/$slug/chat/$chatId/'
      path: '/chat/$chatId'
      fullPath: '/$type/$slug/chat/$chatId/'
      preLoaderRoute: typeof TypeSlugChatChatIdIndexRouteImport
      parentRoute: typeof TypeSlugRouteRoute
    }
  }
}

interface TypeSlugRouteRouteChildren {
  TypeSlugIndexRoute: typeof TypeSlugIndexRoute
  TypeSlugPortcosIndexRoute: typeof TypeSlugPortcosIndexRoute
  TypeSlugChatChatIdIndexRoute: typeof TypeSlugChatChatIdIndexRoute
}

const TypeSlugRouteRouteChildren: TypeSlugRouteRouteChildren = {
  TypeSlugIndexRoute: TypeSlugIndexRoute,
  TypeSlugPortcosIndexRoute: TypeSlugPortcosIndexRoute,
  TypeSlugChatChatIdIndexRoute: TypeSlugChatChatIdIndexRoute,
}

const TypeSlugRouteRouteWithChildren = TypeSlugRouteRoute._addFileChildren(
  TypeSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TypeSlugRouteRoute: TypeSlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
